/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package filmes;

import arquivo.ArquivoFilme;
import javax.swing.JOptionPane;

/**
 *
 * @author pedrojorge
 */
public class CadastroFilme extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroFilme
     */
    public CadastroFilme() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LouD = new javax.swing.ButtonGroup();
        bntConfirma = new javax.swing.JButton();
        bntCancela = new javax.swing.JButton();
        lblNome = new javax.swing.JLabel();
        lblFaixa = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        cbxFaixa = new javax.swing.JComboBox();
        lblTipo = new javax.swing.JLabel();
        rbntLegendado = new javax.swing.JRadioButton();
        rbntDublado = new javax.swing.JRadioButton();

        bntConfirma.setBackground(new java.awt.Color(255, 51, 102));
        bntConfirma.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bntConfirma.setText("Confirma");
        bntConfirma.setContentAreaFilled(false);
        bntConfirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntConfirmaActionPerformed(evt);
            }
        });

        bntCancela.setBackground(new java.awt.Color(204, 204, 255));
        bntCancela.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bntCancela.setText("Cancela");
        bntCancela.setContentAreaFilled(false);
        bntCancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCancelaActionPerformed(evt);
            }
        });

        lblNome.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblNome.setText("Nome:");

        lblFaixa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblFaixa.setText("Faixa:");

        cbxFaixa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Livre", "12", "14", "16", "18" }));

        lblTipo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTipo.setText("Tipo:");

        LouD.add(rbntLegendado);
        rbntLegendado.setText("Legendado");

        LouD.add(rbntDublado);
        rbntDublado.setText("Dublado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bntConfirma)
                        .addGap(46, 46, 46)
                        .addComponent(bntCancela))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lblTipo)
                        .addGap(46, 46, 46)
                        .addComponent(rbntLegendado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbntDublado)))
                .addContainerGap(65, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFaixa)
                    .addComponent(lblNome))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxFaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNome))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFaixa)
                    .addComponent(cbxFaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipo)
                    .addComponent(rbntLegendado)
                    .addComponent(rbntDublado))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntConfirma)
                    .addComponent(bntCancela))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntConfirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntConfirmaActionPerformed
        ArquivoFilme out = new ArquivoFilme();
        String resutado = out.add(txtNome.getText(), (String) cbxFaixa.getSelectedItem(),(String)LouD.toString());
        if(resutado.equals("cadastrado com suceso")){
            txtNome.setText("");
            
        }
        JOptionPane.showMessageDialog(null, resutado);

    }//GEN-LAST:event_bntConfirmaActionPerformed

    private void bntCancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCancelaActionPerformed
        int resp = JOptionPane.showConfirmDialog(null, "Deseja fechar a tela?", "Confirmar fechamento", JOptionPane.YES_NO_OPTION);
        if (resp==0)
        this.dispose();
    }//GEN-LAST:event_bntCancelaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup LouD;
    private javax.swing.JButton bntCancela;
    private javax.swing.JButton bntConfirma;
    private javax.swing.JComboBox cbxFaixa;
    private javax.swing.JLabel lblFaixa;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JRadioButton rbntDublado;
    private javax.swing.JRadioButton rbntLegendado;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
