/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package funcinario;

import arquivo.ArquivoF;
import javax.swing.JOptionPane;

/**
 *
 * @author pedrojorge
 */
public class CadastroFuncinarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroFuncinarios
     */
    public CadastroFuncinarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblLoing = new javax.swing.JLabel();
        lblSeha = new javax.swing.JLabel();
        txtLoing = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        txtConfirmaSenha = new javax.swing.JPasswordField();
        lblConfirmaSenha = new javax.swing.JLabel();
        bntConfirma = new javax.swing.JButton();
        bntCancela = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        lblNome.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblNome.setText("Nome:");

        lblLoing.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblLoing.setText("Loing:");

        lblSeha.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSeha.setText("Senha:");

        lblConfirmaSenha.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblConfirmaSenha.setText("Confirma Senha:");

        bntConfirma.setBackground(new java.awt.Color(255, 51, 102));
        bntConfirma.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bntConfirma.setText("Confirma");
        bntConfirma.setContentAreaFilled(false);
        bntConfirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntConfirmaActionPerformed(evt);
            }
        });

        bntCancela.setBackground(new java.awt.Color(204, 204, 255));
        bntCancela.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bntCancela.setText("Cancela");
        bntCancela.setContentAreaFilled(false);
        bntCancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCancelaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblLoing)
                            .addComponent(lblNome))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                            .addComponent(txtLoing)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblConfirmaSenha)
                            .addComponent(lblSeha)
                            .addComponent(bntConfirma))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSenha)
                            .addComponent(txtConfirmaSenha)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bntCancela)
                                .addGap(0, 92, Short.MAX_VALUE)))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNome))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLoing)
                    .addComponent(txtLoing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSeha)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConfirmaSenha)
                    .addComponent(txtConfirmaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntConfirma)
                    .addComponent(bntCancela))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntCancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCancelaActionPerformed
        int resp = JOptionPane.showConfirmDialog(null, "Deseja fechar a tela?", "Confirmar fechamento", JOptionPane.YES_NO_OPTION);
        if (resp==0)
            this.dispose(); 
    }//GEN-LAST:event_bntCancelaActionPerformed

    private void bntConfirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntConfirmaActionPerformed
        ArquivoF out = new ArquivoF();
        String resutado = out.add(txtConfirmaSenha.getText(),txtLoing.getText(),txtSenha.getText(),txtNome.getText());
        if(resutado.equals("cadastrado com suceso")){    
            txtConfirmaSenha.setText("");
            txtLoing.setText("");
            txtNome.setText("");
            txtSenha.setText("");
        }
        JOptionPane.showMessageDialog(null, resutado);
            
    }//GEN-LAST:event_bntConfirmaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntCancela;
    private javax.swing.JButton bntConfirma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblConfirmaSenha;
    private javax.swing.JLabel lblLoing;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSeha;
    private javax.swing.JPasswordField txtConfirmaSenha;
    private javax.swing.JTextField txtLoing;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
